/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_JPayApplication */

#ifndef _Included_application_JPayApplication
#define _Included_application_JPayApplication
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jstring JNICALL Java_application_JPayApplication_getCtime(JNIEnv *,
		jobject, jstring);

/*
 * Class:     application_JPayApplication
 * Method:    getKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_application_JPayApplication_getKey(JNIEnv *,
		jobject);

/*
 * Class:     application_JPayApplication
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_application_JPayApplication_getIv(JNIEnv *,
		jobject);

#ifdef __cplusplus
}
#endif
#endif
